services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: projetoacbr/acbrlib_php:latest
    container_name: acbrlib_php
    restart: always
    ports:
      - "8000:80"
    networks:
      - acbr_network

networks:
  acbr_network:
    driver: bridge
