# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM-Publisher

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-acbrlib-comum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          cd NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlib-node-comum
          npm install -g typescript yalc 
          npm i
          npm run build
          yalc publish
          

  build-acbrlib-nfe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          cd NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlibnfe-node
          npm install -g typescript yalc 
          npm i
          npm run build
          yalc publish
  
  build-acbrlib-mdfe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          cd NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlibmdfe-node
          npm install -g typescript yalc 
          npm i
          npm run build
          yalc publish
        
  build-acbrlib-cep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          cd NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlibcep-node
          npm install -g typescript yalc 
          npm i
          npm run build
          yalc publish
          

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: |
          cd NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlib-node-comum
          npm publish

          cd NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlibnfe-node
          npm publish

          NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlibmdfe-node
          npm publish

          cd NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlibcep-node
          npm publish

        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
