# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:  # <-- permite rodar manualmente
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: cd NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlib-node-comum
      - run: npm i && \
          npm run build && \
          yalc publish && \
      - run: npm teste

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
     #- run: npm ci
     # - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
