name: NPM-Publisher

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install -g typescript yalc

      - name: Build comum
        run: |
          cd NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlib-node-comum
          npm install
          npm run build
          yalc publish

      - name: Build NFe
        run: |
          cd NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlibnfe-node
          npm install
          yalc add acbrlib-node-comum
          npm run build
          yalc publish

      - name: Build MDFe
        run: |
          cd NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlibmdfe-node
          npm install
          yalc add acbrlib-node-comum
          npm run build
          yalc publish

      - name: Build CEP
        run: |
          cd NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlibcep-node
          npm install
          yalc add acbrlib-node-comum
          npm run build
          yalc publish

  publish-npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: |
          cd NODE/acbrlib-node-exemplo/acbrlib-nodejs/acbrlib-node-comum
          npm publish

          cd ../acbrlibnfe-node
          npm publish

          ../acbrlibmdfe-node
          npm publish

          cd ../acbrlibcep-node
          npm publish

        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
